version: "3"

services:
  api:
    container_name: serveur-web
    image: api/php5.6-apache:latest
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    networks:
      serveur-web:
        ipv4_address: 192.168.102.50
    depends_on:
      - serveur-BD
    links:
      - serveur-BD
    volumes:
      - ./public:/var/www/html

  serveur-BD:
    image: api/database:latest
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    command: "--innodb-use-native-aio=0"
    container_name: serveur-BD
    restart: always
    tty: true
    volumes:
      - serveur-BD:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      serveur-web:
        ipv4_address: 192.168.102.51

volumes:
  serveur-BD:
    driver: local

networks:
  serveur-web:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.102.0/24